// omnichannel-chat-sdk/angular-botframework-webchat-control/src/app/app.component.ts
import { Component, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';
import { OmnichannelChatSDK } from '@microsoft/omnichannel-chat-sdk';
import { WebChatControlService } from './web-chat-control.service';
import createCustomStore from './createCustomStore';
import createAvatarMiddleware from './createAvatarMiddleware';
import createActivityMiddleware from './createActivityMiddleware';
import { createDataMaskingMiddleware } from './createDataMaskingMiddleware';
import fetchDebugConfig from 'src/utils/fetchDebugConfig';
import fetchOmnichannelConfig from 'src/utils/fetchOmnichannelConfig';
import fetchTelemetryConfig from 'src/utils/fetchTelemetryConfig';

const omnichannelConfig = fetchOmnichannelConfig();
const telemetryConfig: any = fetchTelemetryConfig();
const debugConfig = fetchDebugConfig();

console.log(`%c [OmnichannelConfig]`, 'background-color:#001433;color:#fff');
console.log(omnichannelConfig);

console.log(`%c [debugConfig]`, 'background-color:#001433;color:#fff');
console.log(debugConfig);

console.log(`%c [telemetryConfig]`, 'background-color:#001433;color:#fff');
console.log(telemetryConfig);

const avatarMiddleware: any = createAvatarMiddleware();
const activityMiddleware: any = createActivityMiddleware();

const styleOptions = {
  bubbleBorderRadius: 10,
  bubbleNubSize: 10,
  bubbleNubOffset: 15,

  bubbleFromUserBorderRadius: 10,
  bubbleFromUserNubSize: 10,
  bubbleFromUserNubOffset: 15,
  bubbleFromUserBackground: 'rgb(246, 246, 246)'
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-botframework-webchat-control';
  webChat: any = null;
  chatSDK: OmnichannelChatSDK | null = null;
  chatAdapter: any = null;
  loading: boolean = false;
  hasChatStarted: boolean = false;
  webChatStore: any = null;

  constructor(
    private readonly webChatControlService: WebChatControlService, @Inject(DOCUMENT) private readonly document: any
  ) {}

  async ngOnInit() {
    console.log("[ngOnInit]");

    this.webChatControlService.lazyLoad().subscribe(async (_) => {
      this.webChat = (window as any).WebChat;

      // console.log(this.webChat);

      const chatSDKConfig = {
        ...telemetryConfig
      }

      const chatSDK = new OmnichannelChatSDK(omnichannelConfig, chatSDKConfig);
      console.log((chatSDK as any).chatSDKConfig);

      chatSDK.setDebug(!debugConfig.disable);

      await chatSDK.initialize();

      this.chatSDK = chatSDK;
      this.webChat = (window as any).WebChat;

      const liveChatContext = localStorage.getItem('liveChatContext');
      if (liveChatContext && Object.keys(JSON.parse(liveChatContext)).length > 0) {
        console.log("[liveChatContext]");
        console.log(liveChatContext);
      }
    });
  }

  async startChat() {
    console.log('[startChat]');

    const dataMaskingRules = await this.chatSDK?.getDataMaskingRules();
    console.log(dataMaskingRules);

    const store = createCustomStore();
    this.webChatStore = store.create();

    store.subscribe('DataMasking', createDataMaskingMiddleware(dataMaskingRules));

    const optionalParams: any = {};

    // Check for active conversation in cache
    const cachedLiveChatContext = localStorage.getItem('liveChatContext');
    if (cachedLiveChatContext && Object.keys(JSON.parse(cachedLiveChatContext)).length > 0) {
      console.log("[liveChatContext]");
      optionalParams.liveChatContext = JSON.parse(cachedLiveChatContext);
    }

    this.hasChatStarted = true;
    this.loading = true;

    await this.chatSDK?.startChat(optionalParams);

    // Cache current conversation context
    const liveChatContext = await this.chatSDK?.getCurrentLiveChatContext();
    if (liveChatContext &&  Object.keys(liveChatContext).length) {
      localStorage.setItem('liveChatContext', JSON.stringify(liveChatContext));
    }

    const chatAdapter = await this.chatSDK?.createChatAdapter();
    this.chatAdapter = chatAdapter;

    this.loading = false;

    this.webChat.renderWebChat(
      {
        directLine: chatAdapter,
        sendTypingIndicator: true,
        styleOptions,
        store: this.webChatStore,
        avatarMiddleware,
        activityMiddleware
      },
      this.document.getElementById('chat-container')
    );
  }

  async endChat() {
    console.log('[endChat]');
    await this.chatSDK?.endChat();
    this.hasChatStarted = false;

    // Remove all children
    const parent = this.document.getElementById('chat-container');
    while (parent.firstChild) {
      parent.firstChild.remove()
    }
  }
}

<div id="root">
  <div id="chat-root" *ngIf="hasChatStarted">
    <div class="chat-header">LiveChat with Omnichannel Chat SDK <span (click)="endChat()"> ❌ </span> </div>
    <div id="loading-screen" *ngIf="loading">
      <span id="loader"> 👀 </span>
    </div>
    <div id="chat-container"></div>
  </div>
  <div id="chat-button" *ngIf="!hasChatStarted && !loading" (click)="startChat()">
    <span> 👋 </span>
  </div>
</div>

// omnichannel-chat-sdk/react-botframework-webchat-control/src/App.tsx
import { useCallback, useEffect, useState } from 'react'
import { OmnichannelChatSDK } from '@microsoft/omnichannel-chat-sdk';
import ReactWebChat from 'botframework-webchat';
import { version as chatSDKversion } from '@microsoft/omnichannel-chat-sdk/package.json';
import { version as OCSDKVersion } from '@microsoft/ocsdk/package.json';
import { version as webChatVersion } from 'botframework-webchat/package.json';
import { version as chatAdapterVersion } from '@microsoft/botframework-webchat-adapter-azure-communication-chat/package.json';
import AppConfig from './configs/AppConfig';
import fetchDebugConfig from './utils/fetchDebugConfig';
import fetchOmnichannelConfig from './utils/fetchOmnichannelConfig';
import fetchChatSDKConfig from './utils/fetchChatSDKConfig';
import fetchAuthToken from './utils/fetchAuthToken';
import ChatButton from './components/ChatButton/ChatButton';
import ChatHeader from './components/ChatHeader/ChatHeader';
import createActivityMiddleware from './middlewares/native/createActivityMiddleware';
import './App.css';

function App() {
  const [chatSDK, setChatSDK] = useState<OmnichannelChatSDK>();
  const [chatAdapter, setChatAdapter] = useState<any>(undefined);
  const [hasChatStarted, setHasChatStarted] = useState(false);

  useEffect(() => {
    console.log(`ocsdk@${OCSDKVersion}`);
    console.log(`omnichannel-chat-sdk@${chatSDKversion}`);
    console.log(`botframework-webchat@${webChatVersion}`);
    console.log(`botframework-webchat-adapter-azure-communication-chat@${chatAdapterVersion}`)

    const init = async () => {
      const omnichannelConfig = fetchOmnichannelConfig();
      const debugConfig = fetchDebugConfig();
      const authToken = await fetchAuthToken({option: 'api'});
      const chatSDKConfig = fetchChatSDKConfig({ authToken });
      const chatSDK = new OmnichannelChatSDK(omnichannelConfig, chatSDKConfig);
      await chatSDK.initialize();

      if (debugConfig.debug) {
        chatSDK.setDebug(true);
      }

      setChatSDK(chatSDK);

      const chatConfig = await chatSDK.getLiveChatConfig();
      if (AppConfig.ChatSDK.liveChatConfig.log) {
        console.log(chatConfig);
      }

      if (AppConfig.ChatSDK.liveChatContext.reset) {
        localStorage.removeItem('liveChatContext');
      }
    }

    init();
  }, []);

  const startChat = useCallback(async () => {
    if (hasChatStarted) {
      return;
    }

    const optionalParams: any = {};
    if (AppConfig.ChatSDK.liveChatContext.retrieveFromCache) {
      const cachedLiveChatContext = localStorage.getItem('liveChatContext');
      if (cachedLiveChatContext && Object.keys(JSON.parse(cachedLiveChatContext)).length > 0) {
        AppConfig.ChatSDK.liveChatContext && console.log("[liveChatContext]");
        optionalParams.liveChatContext = JSON.parse(cachedLiveChatContext);
      }
    }

    await chatSDK?.startChat(optionalParams);

    if (AppConfig.ChatSDK.liveChatContext.cache) {
      const liveChatContext = await chatSDK?.getCurrentLiveChatContext();
      localStorage.setItem('liveChatContext', JSON.stringify(liveChatContext));
    }

    setHasChatStarted(true);
    console.log("Chat started!");
    await chatSDK?.onNewMessage((message: any) => {
      AppConfig.ChatSDK.onNewMessage.log && console.log(`New message!`);
      AppConfig.ChatSDK.onNewMessage.log && console.log(message?.content);
    });

    const chatAdapter = await chatSDK?.createChatAdapter();
    setChatAdapter(chatAdapter);
  }, [chatSDK, hasChatStarted]);

  const endChat = useCallback(async () => {
    if (!hasChatStarted) {
      return;
    }

    await chatSDK?.endChat();

    if (AppConfig.ChatSDK.liveChatContext.cache) {
      localStorage.removeItem('liveChatContext');
    }

    setHasChatStarted(false);
  }, [chatSDK, hasChatStarted]);

  return (
    <>
      <h1>omnichannel-chat-sdk</h1>
      <div className="card">
        <button onClick={startChat}>
          Start Chat
        </button>
        <button onClick={endChat}>
          End Chat
        </button>
      </div>
      { hasChatStarted && <div style={{position: 'absolute', bottom: 20, right: 20, height: 560, width: 350, border: '1px solid rgb(209, 209, 209)', display: 'flex', flexDirection: 'column'}}>
          <ChatHeader onClose={endChat}/>
          {chatAdapter && <ReactWebChat
              directLine={chatAdapter}
              activityMiddleware={createActivityMiddleware()}
            />
          }
        </div>
      }
      { !hasChatStarted && AppConfig.widget.chatButton.disabled === false &&
        <ChatButton handleClick={startChat}/>
      }
    </>
  )
}

export default App;
